version: '3'

services:
  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports: 
      - 5432:5432
    volumes:
      - ~/Documents/Development/sql-alchemy-manipulation/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRE_PASSWORD=root
      - POSTGRE_USER=root
      - POSTGRE_DB=portfolio

    
